[build]
  publish = "public"
  command = "npm run build"
  # command = "npm run build && npm run ipfs-deploy"

[build.environment]
  HUGO_VERSION = "0.67.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://matnoble.netlify.com/*"
  to = "https://matnoble.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.matnoble.com/"
  to = "https://matnoble.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd-linear-system/"
  to = "/posts/svd/svd-apply-to-linear-system/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd1/"
  to = "/posts/svd/svd-mathematical-basis-b/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd/"
  to = "/posts/svd/svd-mathematical-basis-a/"
  status = 301
  force = true