[build]
  publish = "public"
  command = "npm run build"
  # command = "npm run build && npm run ipfs-deploy"

[build.environment]
  HUGO_VERSION = "0.66.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://matnoble.netlify.com/*"
  to = "https://matnoble.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.matnoble.com/"
  to = "https://matnoble.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd-linear-system/"
  to = "/math/linear-algebra/svd/svd-apply-to-linear-system/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd1/"
  to = "/math/linear-algebra/svd/svd-mathematical-basis-b/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd/"
  to = "/math/linear-algebra/svd/svd-mathematical-basis-a/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/shortcodes-practice-tutorial-for-hugo/"
  to = "/tech/hugo/shortcodes-practice-tutorial-for-hugo/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/fem/inequality/"
  to = "/math/fem/inequality/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/ubuntu/install-chromium-browser-ubuntu/"
  to = "/tech/ubuntu/install-chromium-browser-ubuntu/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/ubuntu/python/configure-python-environment-in-ubuntu/"
  to = "/tech/ubuntu/configure-python-environment-in-ubuntu/"
  status = 301
  force = true