[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "npm run build && npm run ipfs-deploy"

[[redirects]]
  from = "https://matnoble.netlify.app/*"
  to = "https://matnoble.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://matnoble.netlify.com/*"
  to = "https://matnoble.me/:splat"
  status = 301
  force = true