[build]
  publish = "public"
  command = "npm run build"
  # command = "npm run build && npm run ipfs-deploy"

[build.environment]
  HUGO_VERSION = "0.66.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://matnoble.netlify.com/*"
  to = "https://matnoble.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.matnoble.com/"
  to = "https://matnoble.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/posts/"
  to = "/archives/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/fem1"
  to = "/math/fem/fem1/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/fem5"
  to = "/math/fem/fem5/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/matrixleastsquares/"
  to = "/math/linear-algebra/matrixleastsquares/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/matrix4basicth/"
  to = "/math/linear-algebra/matrix4basicth/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/rotationandmirroring/"
  to = "/math/linear-algebra/rotationandmirroring/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/hust/"
  to = "/life/hust/undergraduate-admissions-promotion/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/postgraduate_experience_sharing/"
  to = "/life/hust/postgraduate_experience_sharing/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd-linear-system/"
  to = "/math/linear-algebra/svd-apply-to-linear-system/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd1/"
  to = "/math/linear-algebra/svd-mathematical-basis-b/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/svd/"
  to = "/math/linear-algebra/svd-mathematical-basis-a/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/shortcodes-practice-tutorial-for-hugo/"
  to = "/tech/hugo/shortcodes-practice-tutorial-for-hugo/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/fem/inequality/"
  to = "/math/fem/inequality/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/ubuntu/install-chromium-browser-ubuntu/"
  to = "/tech/ubuntu/install-chromium-browser-ubuntu/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/ubuntu/python/configure-python-environment-in-ubuntu/"
  to = "/tech/ubuntu/configure-python-environment-in-ubuntu/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/surfacego/"
  to = "/tech/reviews/surfacego/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/transferfiles/"
  to = "/tech/programming/transferfiles/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/install-texlive/"
  to = "/tech/ubuntu/install-texlive/"
  status = 301
  force = true

[[redirects]]
  from = "/posts/linear-algebra-problem-set/"
  to = "/math/linear-algebra/linear-algebra-problem-set/"
  status = 301
  force = true